"""Spinor Wannier90 Hamiltonian helpers used by native exchange."""

from __future__ import annotations

import argparse
import os

import numpy as np

from slw.core.wannier_io import read_wannier_hr, write_wannier_hr
from slw.exchange.kernels.spinor import normalize_spin_direction, spinor_from_collinear
from slw.soc.spinor import normalize_groupby, spin_major_to_groupby_indices


def _read_wannier_hr_compat(path):
    parsed = read_wannier_hr(path)
    if len(parsed) == 4:
        dim, _nrpts, degens, hmap = parsed
        return int(dim), list(degens), hmap
    if len(parsed) == 3:
        dim, degens, hmap = parsed
        return int(dim), list(degens), hmap
    raise ValueError(f"Unexpected read_wannier_hr return length={len(parsed)} for {path}")


def _resolve_hr_path(path=None, prefix=None):
    if path:
        return path
    if not prefix:
        raise ValueError("Provide either explicit hr path or prefix")
    return f"{prefix}_hr.dat"


def _basis_permutation(nwan, groupby):
    mode = normalize_groupby(groupby)
    return spin_major_to_groupby_indices(int(nwan), mode), mode.value


def _read_centres_xyz(path):
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()
    if len(lines) < 2:
        raise ValueError(f"Invalid centres file: {path}")
    total = int(lines[0].strip())
    body = lines[2:]
    if len(body) < total:
        raise ValueError(f"centres count mismatch in {path}: header={total}, body={len(body)}")
    return body[:total]


def _split_centres_body(body, nwan):
    if len(body) < int(nwan):
        raise ValueError(f"centres body has {len(body)} rows, expected at least nwan={nwan}")
    return body[: int(nwan)], body[int(nwan) :]


def _centres_default_output(out_hr):
    base = os.path.basename(str(out_hr))
    if base.endswith("_hr.dat"):
        return os.path.join(os.path.dirname(os.path.abspath(out_hr)), base[:-7] + "_centres.xyz")
    stem, _ext = os.path.splitext(os.path.abspath(out_hr))
    return stem + "_centres.xyz"


def _normalized_centre_row(line):
    fields = line.split()
    if len(fields) < 4:
        raise ValueError(f"Invalid centres.xyz row: {line!r}")
    try:
        coordinates = tuple(float(value) for value in fields[1:4])
    except ValueError as exc:
        raise ValueError(f"Invalid centres.xyz coordinates: {line!r}") from exc
    return fields[0], coordinates


def _write_spinor_centres(args, nwan, perm, out_hr):
    up_path = args.centres_up
    dn_path = args.centres_dn
    if not up_path and not dn_path:
        if args.centres_output:
            raise ValueError(
                "centres_output requires both centres_up and centres_dn"
            )
        return None
    if not up_path or not dn_path:
        raise ValueError(
            "spinor centres output requires both centres_up and centres_dn"
        )
    up_wann, up_atoms = _split_centres_body(_read_centres_xyz(up_path), nwan)
    dn_wann, dn_atoms = _split_centres_body(_read_centres_xyz(dn_path), nwan)
    if len(up_atoms) != len(dn_atoms):
        raise ValueError(
            f"atom centre row count mismatch: up={len(up_atoms)}, dn={len(dn_atoms)}"
        )
    for index, (up_line, dn_line) in enumerate(zip(up_atoms, dn_atoms, strict=True)):
        up_label, up_xyz = _normalized_centre_row(up_line)
        dn_label, dn_xyz = _normalized_centre_row(dn_line)
        if up_label != dn_label or not np.allclose(up_xyz, dn_xyz, rtol=0.0, atol=1.0e-8):
            raise ValueError(
                f"atomic centre row {index} differs between spin channels"
            )
    atom_lines = up_atoms
    spin_major = up_wann + dn_wann
    ordered_wann = [spin_major[int(i)] for i in np.asarray(perm, dtype=np.int64).tolist()]
    out_path = args.centres_output or _centres_default_output(out_hr)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"    {len(ordered_wann) + len(atom_lines)}\n")
        f.write(f" spinor Wannier centres generated by SLW groupby={args.groupby}\n")
        f.writelines(line if line.endswith("\n") else line + "\n" for line in ordered_wann)
        f.writelines(line if line.endswith("\n") else line + "\n" for line in atom_lines)
    return out_path


def build_spinor_hr(args):
    up_path = _resolve_hr_path(args.up_hr, args.prefix_up)
    dn_path = _resolve_hr_path(args.dn_hr, args.prefix_dn)
    out_path = args.output
    if out_path is None:
        out_prefix = args.out_prefix or args.prefix or "spinor_soc"
        out_path = f"{out_prefix}_hr.dat"

    dim_up, degens_up, h_up = _read_wannier_hr_compat(up_path)
    dim_dn, degens_dn, h_dn = _read_wannier_hr_compat(dn_path)
    if dim_up != dim_dn:
        raise ValueError(f"hr.dat dimension mismatch: up={dim_up}, dn={dim_dn}")
    if set(h_up) != set(h_dn):
        missing_dn = sorted(set(h_up) - set(h_dn))
        missing_up = sorted(set(h_dn) - set(h_up))
        raise ValueError(f"R-vector mismatch: missing_dn={missing_dn[:5]} missing_up={missing_up[:5]}")
    if len(degens_up) != len(h_up):
        raise ValueError(f"up degeneracy count={len(degens_up)} does not match nrpts={len(h_up)}")
    if len(degens_dn) != len(h_dn):
        raise ValueError(f"dn degeneracy count={len(degens_dn)} does not match nrpts={len(h_dn)}")
    up_r = list(h_up)
    dn_r = list(h_dn)
    up_degeneracy = dict(zip(up_r, degens_up, strict=True))
    dn_degeneracy = dict(zip(dn_r, degens_dn, strict=True))
    inconsistent = [
        r for r in up_r if up_degeneracy[r] != dn_degeneracy[r]
    ]
    if inconsistent:
        raise ValueError(
            "up/down R-point degeneracies differ for "
            f"{inconsistent[:5]}"
        )

    nwan = int(dim_up)
    nvec = normalize_spin_direction(args.spin_direction)
    spinor = {}
    for r in h_up:
        spinor[r] = spinor_from_collinear(h_up[r], h_dn[r], n=nvec)

    perm, groupby = _basis_permutation(nwan, args.groupby)
    if groupby != "spin":
        spinor = {r: h[np.ix_(perm, perm)] for r, h in spinor.items()}

    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    header = (
        "SLW spinor hr from collinear up/down"
        f"; spin_direction={','.join(f'{x:.10g}' for x in nvec)}"
        "; additional_soc=none"
        f"; groupby={groupby}"
    )
    output_degeneracies = [up_degeneracy[r] for r in sorted(spinor)]
    write_wannier_hr(
        out_path,
        2 * nwan,
        output_degeneracies,
        spinor,
        header=header,
    )
    centres_path = _write_spinor_centres(args, nwan, perm, out_path)
    print("[spinor-soc-hr] summary", flush=True)
    print(f"  up_hr: {up_path}", flush=True)
    print(f"  dn_hr: {dn_path}", flush=True)
    print(f"  output: {out_path}", flush=True)
    print(f"  nwan: {nwan} -> spinor_dim: {2 * nwan}", flush=True)
    print(f"  nrpts: {len(spinor)}", flush=True)
    print(f"  spin_direction: {nvec.tolist()}", flush=True)
    print(f"  groupby: {groupby}", flush=True)
    if centres_path:
        print(f"  centres_output: {centres_path}", flush=True)
    return out_path


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--prefix", default=None, help="Base prefix; defaults up/dn/output to <prefix>_up/_dn/_hr.dat patterns")
    ap.add_argument("--prefix_up", default=None, help="Spin-up prefix; reads <prefix_up>_hr.dat")
    ap.add_argument("--prefix_dn", default=None, help="Spin-down prefix; reads <prefix_dn>_hr.dat")
    ap.add_argument("--up_hr", default=None, help="Explicit spin-up hr.dat path")
    ap.add_argument("--dn_hr", default=None, help="Explicit spin-down hr.dat path")
    ap.add_argument("-o", "--output", default=None, help="Output spinor hr.dat path")
    ap.add_argument("--out_prefix", default=None, help="Output prefix; writes <out_prefix>_hr.dat if --output is omitted")
    ap.add_argument(
        "--groupby",
        choices=["spin", "orbital"],
        required=True,
        help="TB2J output layout: all spin sectors or interleaved spin per orbital.",
    )
    ap.add_argument("--centres_up", default=None, help="Spin-up centres.xyz file")
    ap.add_argument("--centres_dn", default=None, help="Spin-down centres.xyz file")
    ap.add_argument("--centres_output", default=None, help="Output spinor centres.xyz path")
    ap.add_argument("--spin_direction", type=float, nargs=3, default=[0.0, 0.0, 1.0])
    args = ap.parse_args()

    if args.prefix:
        args.prefix_up = args.prefix_up or f"{args.prefix}_up"
        args.prefix_dn = args.prefix_dn or f"{args.prefix}_dn"
        args.out_prefix = args.out_prefix or args.prefix
    build_spinor_hr(args)


if __name__ == "__main__":
    main()
