"""Native mode bridges: Fortran axes, mass units, BdG normalization and gauge."""

from pathlib import Path

import h5py
import numpy as np
import pytest

from slw.core.constants import RY_TO_EV
from slw.wtorque.native_modes import (
    QE_AMU_RY, load_tb2j_isotropic_model, native_magnon_modes, native_phonon_modes,
    validate_phonons_against_qe_dyn_xml,
)
from slw.wtorque.projection.magnon import paraunitarity_residual
from slw.wtorque.projection.phonon import phonon_zero_point_displacement


def _epr_fixture(path: Path) -> tuple[np.ndarray, np.ndarray]:
    masses_amu = np.array([2.0, 5.0])
    mass_ry = masses_amu * QE_AMU_RY
    positions = np.array([[0.0, 0.0, 0.0], [0.23, 0.0, 0.0]])
    # The interatomic Cartesian block is deliberately not symmetric.  A
    # diagonal/symmetric fixture cannot detect reversed Fortran h5py axes.
    block = np.array([[0.2, 0.4, 0.7], [-0.1, 0.3, 0.8], [0.6, -0.2, 0.1]])
    matrix = np.block([[np.diag([4.0, 5.0, 6.0]), block],
                       [block.T, np.diag([8.0, 9.0, 10.0])]])
    dynamical = matrix * (0.01 / RY_TO_EV)**2
    repeated_mass = np.repeat(mass_ry, 3)
    ifc = dynamical * np.sqrt(repeated_mass[:, None] * repeated_mass[None, :])
    with h5py.File(path, "w") as handle:
        basic = handle.create_group("basic_data")
        for name, data in {
            "at": np.eye(3), "tau": positions, "mass": mass_ry,
            "qc_dim": [1, 1, 1], "nat": 2, "alat": 1.0, "lpolar": False,
        }.items():
            basic[name] = data
        force = handle.create_group("force_constant")
        force["ifc1"] = ifc[:3, :3].T[None]
        force["ifc2"] = ifc[:3, 3:].T[None]
        force["ifc3"] = ifc[3:, 3:].T[None]
    return dynamical, masses_amu


def _exchange_fixture(path: Path, *, fm: bool = False) -> None:
    if fm:
        atoms = "M1 0 0 0 1 2 0 0\n"
        bonds = "M1 M1 (1, 0, 0) 1.0 (1,0,0) 1\nM1 M1 (-1, 0, 0) 1.0 (-1,0,0) 1\n"
    else:
        atoms = "M1 0 0 0 1 2 0 0\nM2 0.5 0 0 1 -2 0 0\n"
        bonds = (
            "M1 M2 (0, 0, 0) -1.0 (0.5,0,0) 0.5\n"
            "M2 M1 (0, 0, 0) -1.0 (-0.5,0,0) 0.5\n"
            "M1 M2 (-1, 0, 0) -1.0 (-0.5,0,0) 0.5\n"
            "M2 M1 (1, 0, 0) -1.0 (0.5,0,0) 0.5\n"
        )
    path.write_text(
        "Exchange parameters generated by TB2J test\n"
        "Cell (Angstrom):\n1 0 0\n0 1 0\n0 0 1\n"
        "Atoms:\nAtom_number x y z w_charge M(x) M(y) M(z)\n" + atoms +
        "Exchange:\ni j R J_iso(meV) vector distance(A)\n" + bonds
    )


def test_epr_fortran_axes_and_rydberg_mass_units(tmp_path: Path) -> None:
    path = tmp_path / "fixture.h5"
    expected, masses = _epr_fixture(path)
    result = native_phonon_modes(path, [[0.31, 0.0, 0.0]], gauge="cell")
    np.testing.assert_allclose(result.dynamical_matrix_ry2[0], expected, rtol=1e-14, atol=1e-20)
    np.testing.assert_allclose(result.masses_amu, masses, rtol=1e-14)
    np.testing.assert_allclose(result.energies_eV[0], np.sqrt(np.linalg.eigvalsh(expected)) * RY_TO_EV)
    vectors = result.eigenvectors[0].reshape(6, 6)
    np.testing.assert_allclose(vectors.conj().T @ vectors, np.eye(6), atol=1e-14)
    xi = phonon_zero_point_displacement(result.energies_eV[0], result.masses_amu, result.eigenvectors[0])
    # Independent SI formula confirms the Rydberg-mass factor of two.
    expected_xi = result.eigenvectors[0] * np.sqrt(
        (6.62607015e-34 / (2*np.pi))**2 /
        (2*masses[:, None]*1.66053906660e-27 * result.energies_eV[0, None, :] * 1.602176634e-19)
    )[:, None, :] / 1e-10
    np.testing.assert_allclose(xi, expected_xi, rtol=1e-9)


def test_phonon_atomic_gauge_and_q_pair(tmp_path: Path) -> None:
    path = tmp_path / "fixture.h5"
    _epr_fixture(path)
    q = np.array([[1/3, 0, 0], [-1/3, 0, 0]])
    cell = native_phonon_modes(path, q, gauge="cell")
    atomic = native_phonon_modes(path, q, gauge="atomic")
    phase = np.repeat(np.exp(-2j*np.pi*(q @ atomic.atom_positions_frac.T)), 3, axis=1)
    expected = phase[:, :, None] * cell.dynamical_matrix_ry2 * phase[:, None, :].conj()
    np.testing.assert_allclose(atomic.dynamical_matrix_ry2, expected, atol=1e-20)
    np.testing.assert_allclose(atomic.dynamical_matrix_ry2[1], atomic.dynamical_matrix_ry2[0].conj(), atol=1e-20)
    np.testing.assert_allclose(atomic.energies_eV, cell.energies_eV, atol=1e-15)
    np.testing.assert_allclose(atomic.eigenvectors[1], atomic.eigenvectors[0].conj(), atol=1e-14)
    separately_called = native_phonon_modes(path, q[1:], gauge="atomic")
    np.testing.assert_allclose(separately_called.eigenvectors[0], atomic.eigenvectors[0].conj(), atol=1e-14)


def test_nonpositive_phonon_is_not_shifted(tmp_path: Path) -> None:
    path = tmp_path / "fixture.h5"
    _epr_fixture(path)
    with h5py.File(path, "a") as handle:
        handle["force_constant/ifc1"][...] = 0.0
        handle["force_constant/ifc2"][...] = 0.0
    with pytest.raises(ValueError, match="nonpositive native phonon"):
        native_phonon_modes(path, [[0.2, 0, 0]])


def test_independent_qe_xml_comparison_checks_full_matrix(tmp_path: Path) -> None:
    path = tmp_path / "fixture.h5"
    expected, masses = _epr_fixture(path)
    modes = native_phonon_modes(path, [[0.3, 0, 0]], gauge="atomic")
    mass_ry = np.repeat(masses*QE_AMU_RY, 3)
    phi = expected * np.sqrt(mass_ry[:, None]*mass_ry[None, :])
    xml = ["<Root><GEOMETRY_INFO><AT>1 0 0 0 1 0 0 0 1</AT></GEOMETRY_INFO>",
           "<DYNAMICAL_MAT_.1><Q_POINT>0.3 0 0</Q_POINT>"]
    for atom_i in range(2):
        for atom_j in range(2):
            block = phi[3*atom_i:3*atom_i+3, 3*atom_j:3*atom_j+3]
            xml.append(f"<PHI.{atom_i+1}.{atom_j+1}>")
            for cart_j in range(3):
                for cart_i in range(3):
                    xml.append(f"{block[cart_i, cart_j]:.17g} 0")
            xml.append(f"</PHI.{atom_i+1}.{atom_j+1}>")
    xml.append("</DYNAMICAL_MAT_.1></Root>")
    dyn = tmp_path / "fixture.dyn1.xml"
    dyn.write_text("\n".join(xml))
    report = validate_phonons_against_qe_dyn_xml(modes, [dyn])
    assert report["status"] == "pass"
    assert report["max_matrix_relative_residual"] < 1e-14
    with pytest.raises(ValueError, match="lacks requested q"):
        validate_phonons_against_qe_dyn_xml(modes, [])
    dyn.write_text(dyn.read_text().replace(f"{phi[0, 0]:.17g} 0", "0 0"))
    with pytest.raises(ValueError, match="disagree"):
        validate_phonons_against_qe_dyn_xml(modes, [dyn])


def test_afm_analytic_energy_source_axis_and_paraunitarity(tmp_path: Path) -> None:
    path = tmp_path / "exchange.out"
    _exchange_fixture(path)
    q = np.array([[1/3, 0, 0], [-1/3, 0, 0]])
    result = native_magnon_modes(path, q, spin_lengths=[1, 1], source_directed_bond_weight=1.0)
    # Mate-complete TB2J H=-sum J e.e: chain AFM has E=4|J sin(pi q)|/S.
    np.testing.assert_allclose(result.energies_eV, 4*np.sin(np.pi/3)*1e-3, atol=1e-16)
    np.testing.assert_allclose(result.local_frames[:, 2], [[1, 0, 0], [-1, 0, 0]])
    np.testing.assert_allclose(np.cross(result.local_frames[:, 0], result.local_frames[:, 1]), result.local_frames[:, 2])
    assert max(paraunitarity_residual(t) for t in result.transform) < 1e-14
    assert result.diagnostics["J_source_to_native_factor"] == 2
    rows = [2, 3, 0, 1]
    np.testing.assert_allclose(result.transform[0, :, 2:], result.transform[1, rows, :2].conj(), atol=1e-14)
    np.testing.assert_allclose(result.transform[1, :, 2:], result.transform[0, rows, :2].conj(), atol=1e-14)


def test_magnon_atomic_gauge_uses_same_phase_for_both_nambu_sectors(tmp_path: Path) -> None:
    path = tmp_path / "exchange.out"
    _exchange_fixture(path)
    q = np.array([[0.3, 0, 0]])
    args = dict(spin_lengths=[1, 1], source_directed_bond_weight=1.0)
    cell = native_magnon_modes(path, q, gauge="cell", **args)
    atomic = native_magnon_modes(path, q, gauge="atomic", **args)
    phase = np.exp(-2j*np.pi*(q @ cell.magnetic_site_positions.T))
    np.testing.assert_allclose(atomic.transform, np.concatenate((phase, phase), axis=1)[:, :, None]*cell.transform, atol=1e-14)


def test_fm_completes_full_nambu_modes(tmp_path: Path) -> None:
    path = tmp_path / "exchange.out"
    _exchange_fixture(path, fm=True)
    result = native_magnon_modes(path, [[0.25, 0, 0]], spin_lengths=[1], source_directed_bond_weight=1.0)
    np.testing.assert_allclose(result.energies_eV, 0.004, atol=1e-16)
    assert result.transform.shape == (1, 2, 2)
    assert paraunitarity_residual(result.transform[0]) < 1e-14


def test_afm_goldstone_and_missing_mate_are_rejected(tmp_path: Path) -> None:
    path = tmp_path / "exchange.out"
    _exchange_fixture(path)
    with pytest.raises(ValueError, match="Goldstone"):
        native_magnon_modes(path, [[0, 0, 0]], spin_lengths=[1, 1], source_directed_bond_weight=1.0)
    path.write_text(path.read_text().replace("M2 M1 (1, 0, 0) -1.0 (0.5,0,0) 0.5\n", ""))
    with pytest.raises(ValueError, match="missing reciprocal"):
        load_tb2j_isotropic_model(path, source_directed_bond_weight=1.0)
