"""qe2pert/Perturbo Wigner-Seitz cell helpers.

This module ports the WS-vector ordering used by qe2pert's
``wigner_seitz_cell.f90``.  The returned vector order is the order used for
the real-space axes in ``prefix_epr.h5`` payloads.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np


WS_SEARCH_RANGE = 3
EPS6 = 1.0e-6


@dataclass(frozen=True)
class VectorImages:
    """Candidate image vectors generated by qe2pert ``init_rvec_images``."""

    vec: np.ndarray
    idx: np.ndarray
    nim: np.ndarray
    mesh: tuple[int, int, int]


@dataclass(frozen=True)
class WSCell:
    """Selected Wigner-Seitz vectors for one two-center object."""

    vectors: np.ndarray
    ndeg: np.ndarray
    raw_indices: np.ndarray

    @property
    def nr(self) -> int:
        return int(self.vectors.shape[0])


def _as_mesh(mesh) -> tuple[int, int, int]:
    arr = tuple(int(x) for x in mesh)
    if len(arr) != 3 or any(x <= 0 for x in arr):
        raise ValueError(f"mesh must contain three positive integers, got {mesh!r}")
    return arr


def _as_at(at) -> np.ndarray:
    out = np.asarray(at, dtype=np.float64)
    if out.shape != (3, 3):
        raise ValueError(f"at must have shape (3, 3), got {out.shape}")
    return out


def _as_vec3(vec, name: str) -> np.ndarray:
    out = np.asarray(vec, dtype=np.float64).reshape(-1)
    if out.shape != (3,):
        raise ValueError(f"{name} must have length 3, got shape {out.shape}")
    return out


def qe2pert_length(vec, at) -> np.ndarray:
    """Return ``|at @ vec|`` for one or more crystal-coordinate vectors."""

    at_arr = _as_at(at)
    v = np.asarray(vec, dtype=np.float64)
    if v.shape == (3,):
        return np.linalg.norm(at_arr @ v)
    if v.ndim != 2 or v.shape[1] != 3:
        raise ValueError(f"vec must have shape (3,) or (n, 3), got {v.shape}")
    return np.linalg.norm(v @ at_arr.T, axis=1)


def qe2pert_cutoff(mesh, at, *, large_cutoff: bool = False) -> float:
    """Port ``set_cutoff_small``/``set_cutoff_large`` from qe2pert."""

    m = np.asarray(_as_mesh(mesh), dtype=np.int64)
    at_arr = _as_at(at)
    if not large_cutoff:
        m = m // 2 + 1
    signs = np.asarray(
        [(i, j, k) for k in (-1, 1) for j in (-1, 1) for i in (-1, 1)],
        dtype=np.float64,
    )
    vecs = signs * m[None, :]
    return float(np.max(qe2pert_length(vecs, at_arr)))


def init_rvec_images(mesh, at, *, large_cutoff: bool = False) -> VectorImages:
    """Port qe2pert ``init_rvec_images``.

    The base-grid order is Fortran's
    ``do k; do j; do i`` with ``i`` fastest.  Image order is
    ``do mk; do mj; do mi`` with ``mi`` fastest.
    """

    n1, n2, n3 = _as_mesh(mesh)
    at_arr = _as_at(at)
    dims = np.asarray((n1, n2, n3), dtype=np.int64)
    cutoff = qe2pert_cutoff(dims, at_arr, large_cutoff=large_cutoff)

    shifts = np.asarray(
        [
            (mi, mj, mk)
            for mk in range(-WS_SEARCH_RANGE, WS_SEARCH_RANGE + 1)
            for mj in range(-WS_SEARCH_RANGE, WS_SEARCH_RANGE + 1)
            for mi in range(-WS_SEARCH_RANGE, WS_SEARCH_RANGE + 1)
        ],
        dtype=np.int64,
    )
    shift_vecs = shifts * dims[None, :]

    blocks: list[np.ndarray] = []
    idx: list[int] = []
    nim: list[int] = []
    total = 0
    for k in range(n3):
        for j in range(n2):
            for i in range(n1):
                base = np.asarray((i, j, k), dtype=np.int64)
                cand = shift_vecs + base[None, :]
                keep = qe2pert_length(cand, at_arr) < cutoff
                selected = cand[keep]
                if selected.shape[0] < 1:
                    raise RuntimeError("qe2pert init_rvec_images produced nim < 1")
                idx.append(total)
                nim.append(int(selected.shape[0]))
                blocks.append(selected)
                total += int(selected.shape[0])

    return VectorImages(
        vec=np.vstack(blocks).astype(np.int64, copy=False),
        idx=np.asarray(idx, dtype=np.int64),
        nim=np.asarray(nim, dtype=np.int64),
        mesh=(n1, n2, n3),
    )


def set_wigner_seitz_cell(
    images: VectorImages,
    at,
    tau_a,
    tau_b,
    *,
    ref_c=None,
    eps: float = EPS6,
) -> WSCell:
    """Port qe2pert ``set_wigner_seitz_cell``.

    ``tau_a`` and ``tau_b`` are crystal-coordinate positions.  If ``ref_c`` is
    supplied, qe2pert adds ``|R + tau_b - ref_c|`` to the distance.
    """

    at_arr = _as_at(at)
    ta = _as_vec3(tau_a, "tau_a")
    tb = _as_vec3(tau_b, "tau_b")
    rc = None if ref_c is None else _as_vec3(ref_c, "ref_c")

    raw_indices: list[np.ndarray] = []
    ndegs: list[np.ndarray] = []
    for ir in range(int(np.prod(images.mesh))):
        start = int(images.idx[ir])
        stop = start + int(images.nim[ir])
        raw = np.arange(start, stop, dtype=np.int64)
        vec_b = images.vec[start:stop].astype(np.float64) + tb[None, :]
        dist = qe2pert_length(vec_b - ta[None, :], at_arr)
        if rc is not None:
            dist = dist + qe2pert_length(vec_b - rc[None, :], at_arr)
        dist = dist - float(np.min(dist))
        keep = dist < float(eps)
        ndeg = int(np.count_nonzero(keep))
        if ndeg < 1:
            raise RuntimeError("qe2pert set_wigner_seitz_cell produced ndeg < 1")
        raw_indices.append(raw[keep])
        ndegs.append(np.full(ndeg, ndeg, dtype=np.int64))

    # qe2pert collects selected vectors by scanning rvec_images%vec globally.
    raw_all = np.concatenate(raw_indices)
    ndeg_all = np.concatenate(ndegs)
    order = np.argsort(raw_all, kind="stable")
    raw_all = raw_all[order]
    ndeg_all = ndeg_all[order]
    return WSCell(
        vectors=images.vec[raw_all].astype(np.int64, copy=True),
        ndeg=ndeg_all,
        raw_indices=raw_all,
    )


def electron_pair_index(iw: int, jw: int) -> int:
    """Return qe2pert's 1-based triangular pair index for ``iw,jw``."""

    i = int(iw)
    j = int(jw)
    if i <= 0 or j <= 0:
        raise ValueError(f"wannier indices are 1-based positive integers, got {iw}, {jw}")
    lo = min(i, j)
    hi = max(i, j)
    return hi * (hi - 1) // 2 + lo


def triangular_pair_index(i: int, j: int) -> int:
    """Return qe2pert's 1-based triangular index for generic 1-based pairs."""

    return electron_pair_index(i, j)


def build_electron_ws_cell(kmesh, at, wannier_center_cryst, iw: int, jw: int) -> WSCell:
    """Build the ``Re`` WS cell used for electron hopping/e-ph electron axis."""

    centers = np.asarray(wannier_center_cryst, dtype=np.float64)
    if centers.ndim != 2 or centers.shape[1] != 3:
        raise ValueError("wannier_center_cryst must have shape (nwan, 3)")
    images = init_rvec_images(kmesh, at)
    return set_wigner_seitz_cell(images, at, centers[int(iw) - 1], centers[int(jw) - 1])


def build_eph_ws_cells(
    kmesh,
    qmesh,
    at,
    wannier_center_cryst,
    tau_cryst,
    ia: int,
    iw: int,
    jw: int,
    *,
    ph_ref: str = "left",
) -> tuple[WSCell, WSCell]:
    """Build qe2pert e-ph ``(Re, Rp)`` WS cells for ``ep_hop_*_ia_iw_jw``.

    ``iw,jw`` are the Fortran object indices in ``elph%epr(iw,jw,ia)``.  The
    qe2pert HDF5 writer names that object ``ep_hop_*_ia_jw_iw``.

    The phonon WS cell uses the left/``iw`` Wannier center in
    ``set_ws_cell_eph``.  Older shape-only checks may appear to match the
    right/``jw`` center if the HDF5 filename order is read as ``ia_iw_jw``.
    """

    centers = np.asarray(wannier_center_cryst, dtype=np.float64)
    tau = np.asarray(tau_cryst, dtype=np.float64)
    if centers.ndim != 2 or centers.shape[1] != 3:
        raise ValueError("wannier_center_cryst must have shape (nwan, 3)")
    if tau.ndim != 2 or tau.shape[1] != 3:
        raise ValueError("tau_cryst must have shape (nat, 3)")

    iw0 = int(iw) - 1
    jw0 = int(jw) - 1
    ia0 = int(ia) - 1
    ref = str(ph_ref).strip().lower()
    if ref in {"right", "jw", "ket"}:
        ph_center = centers[jw0]
    elif ref in {"left", "iw", "bra"}:
        ph_center = centers[iw0]
    else:
        raise ValueError("ph_ref must be one of: right, jw, ket, left, iw, bra")
    el_images = init_rvec_images(kmesh, at)
    ph_images = init_rvec_images(qmesh, at)
    ws_el = set_wigner_seitz_cell(el_images, at, centers[iw0], centers[jw0])
    ws_ph = set_wigner_seitz_cell(ph_images, at, ph_center, tau[ia0])
    return ws_el, ws_ph


def build_eph_ws_cells_from_hdf5_indices(
    kmesh,
    qmesh,
    at,
    wannier_center_cryst,
    tau_cryst,
    ia: int,
    h5_jw: int,
    h5_iw: int,
    *,
    ph_ref: str = "left",
) -> tuple[WSCell, WSCell]:
    """Build e-ph WS cells from HDF5 dataset indices.

    qe2pert writes ``elph%epr(iw,jw,ia)`` as
    ``ep_hop_[ri]_ia_jw_iw``.  This wrapper makes that filename convention
    explicit.
    """

    return build_eph_ws_cells(
        kmesh,
        qmesh,
        at,
        wannier_center_cryst,
        tau_cryst,
        ia,
        h5_iw,
        h5_jw,
        ph_ref=ph_ref,
    )
