import argparse
import os
import h5py
import numpy as np

from slw.core.set_ws_cell import init_rvec_images, set_wigner_seitz_cell

def triangular_pair_index(i, j):
    """
    1-based index (i, j) for upper triangular matrix.
    Assumes i <= j.
    """
    return j * (j - 1) // 2 + i

def _read_h5_meta(epr_path):
    with h5py.File(epr_path, "r") as h5:
        # epr.h5 file generated by qe2pert has basic_data
        at = np.asarray(h5["basic_data/at"], dtype=np.float64).T
        wc = np.asarray(h5["basic_data/wannier_center_cryst"], dtype=np.float64)
        tau_cart = np.asarray(h5["basic_data/tau"], dtype=np.float64)
        # Convert tau from cartesian to crystal coordinates
        tau = np.linalg.solve(at, tau_cart.T).T

        return {
            "at": at,
            "wc": wc,
            "tau": tau,
            "kc_dim": tuple(int(x) for x in h5["basic_data/kc_dim"][()]),
            "qc_dim": tuple(int(x) for x in h5["basic_data/qc_dim"][()]),
            "nat": int(h5["basic_data/nat"][()]),
            "num_wann": int(h5["basic_data/num_wann"][()]),
        }

def main():
    parser = argparse.ArgumentParser(description="Extract Wigner-Seitz cell rvecs and ndeg from epr.h5")
    parser.add_argument("--epr", required=True, help="Path to input prefix_epr.h5")
    parser.add_argument("--out", default=None, help="Output .h5 file path (default: prefix_wsvec.h5)")
    args = parser.parse_args()

    if args.out is None:
        args.out = os.path.splitext(os.path.basename(args.epr))[0] + "_wsvec.h5"

    print(f"Reading metadata from {args.epr}...")
    meta = _read_h5_meta(args.epr)

    at = meta["at"]
    wc = meta["wc"]
    tau = meta["tau"]
    kc_dim = meta["kc_dim"]
    qc_dim = meta["qc_dim"]
    nwan = meta["num_wann"]
    nat = meta["nat"]

    print("Initializing rvec images for electrons (kc_dim) and phonons (qc_dim)...")
    images_el = init_rvec_images(kc_dim, at)
    images_ph = init_rvec_images(qc_dim, at)

    print(f"Saving Wigner-Seitz vectors to {args.out}...")
    with h5py.File(args.out, "w") as hout:

        # --- Electron WS cells ---
        grp_el = hout.create_group("electron_wannier")
        print(f"Processing electron WS cells ({nwan}x{nwan} pairs)...")
        for jw in range(1, nwan + 1):
            for iw in range(1, jw + 1):
                idx = triangular_pair_index(iw, jw)
                # wc is in crystal coordinates
                ws_rvec, ws_ndeg = set_wigner_seitz_cell(images_el, at, wc[iw - 1], wc[jw - 1])
                # Save to HDF5
                grp_el.create_dataset(f"rvec_{idx}", data=ws_rvec)
                grp_el.create_dataset(f"ndeg_{idx}", data=ws_ndeg)

        # --- Phonon WS cells ---
        grp_ph = hout.create_group("force_constant")
        print(f"Processing phonon WS cells ({nat}x{nat} pairs)...")
        for ja in range(1, nat + 1):
            for ia in range(1, ja + 1):
                idx = triangular_pair_index(ia, ja)
                # tau is in crystal coordinates
                # Note: For set_ws_cell logic, the order of tau_a and tau_b matters (distance = |R + tau_b - tau_a|)
                ws_rvec, ws_ndeg = set_wigner_seitz_cell(images_ph, at, tau[ia - 1], tau[ja - 1])
                # Save to HDF5
                grp_ph.create_dataset(f"rvec_{idx}", data=ws_rvec)
                grp_ph.create_dataset(f"ndeg_{idx}", data=ws_ndeg)

    print("Done!")

if __name__ == "__main__":
    main()
