import numpy as np
import os
import pickle

class WannierInterpolator:
    """Handles real-space transformation and interpolation of EPC matrices."""

    def __init__(self, real_pkl_path):
        """
        Parameters
        ----------
        real_pkl_path : str
            Path to the .real.pkl file generated by compute_epc.
        """
        if not os.path.exists(real_pkl_path):
            raise FileNotFoundError(f"Real-space EPC file not found: {real_pkl_path}")

        with open(real_pkl_path, 'rb') as f:
            data = pickle.load(f)

        self.g_real = data['g_real'] # (nx, ny, nz, qx, qy, qz, Nmodes, Nwan, Nwan)
        self.nk_grid = np.array(data['nk_grid'])
        self.nq_grid = np.array(data['nq_grid'])
        self.cell_prim_ang = data['cell_prim_ang']
        self.points_k = self._get_R_vectors(self.nk_grid)
        self.points_q = self._get_R_vectors(self.nq_grid)

    def _get_R_vectors(self, grid):
        """Get fractional R vectors for the WS cell."""
        rx = np.arange(grid[0]); rx[rx > grid[0]//2] -= grid[0]
        ry = np.arange(grid[1]); ry[ry > grid[1]//2] -= grid[1]
        rz = np.arange(grid[2]); rz[rz > grid[2]//2] -= grid[2]

        # Meshgrid for indices
        ix, iy, iz = np.meshgrid(np.arange(grid[0]), np.arange(grid[1]), np.arange(grid[2]), indexing='ij')

        # Grid of actual R vectors
        RV = np.zeros(tuple(grid) + (3,))
        RV[..., 0] = rx[ix]
        RV[..., 1] = ry[iy]
        RV[..., 2] = rz[iz]
        return RV

    def interpolate(self, k_new, q_new):
        """Perform forward FT to interpolate g(k', q').

        Parameters
        ----------
        k_new, q_new : array_like (3,)
            Fractional coordinates in BZ.
        """
        # Sum_Re,Rp exp(i k'.Re + i q'.Rp) * g(Re, Rp)
        phase_k = np.exp(2j * np.pi * (self.points_k @ k_new))
        phase_q = np.exp(2j * np.pi * (self.points_q @ q_new))

        # Broadcast and sum
        # g_real: (nx, ny, nz, qx, qy, qz, nmodes, nwan, nwan)
        # phase_k: (nx, ny, nz), phase_q: (qx, qy, qz)

        # Nested summing for memory efficiency
        g_k = np.tensordot(phase_k, self.g_real, axes=((0,1,2), (0,1,2))) # Result: (qx, qy, qz, nmodes, nwan, nwan)
        g_final = np.tensordot(phase_q, g_k, axes=((0,1,2), (0,1,2))) # Result: (nmodes, nwan, nwan)

        return g_final

def main():
    # Example usage logic can be added here
    pass

if __name__ == "__main__":
    main()
